Update README.md
mjhea0/awesome-fastapi pull request #73
Opened 2021-02-08 02:38 UTC by orweis

Two new open-source packages on top of FastAPI for Websocket-RPC and Pub/Sub

2021-02-08 02:45 UTC, Kludex requested changes
This PR is probably not going to be accepted with the emojis. The maintainer already expressed his feelings about them on a previous PR. :kissing: 

Do you mind removing them?

Thank you for the contribution! :smile:

2021-02-08 02:45 UTC, Kludex commented on README.md
> +- [⚡ FastAPI Websocket Pub/Sub 🗞️](https://github.com/authorizon/fastapi_websocket_pubsub) - The classic pub/sub pattern made easily accessible and scalable over the web and across your cloud in real
```suggestion
- [FastAPI Websocket Pub/Sub](https://github.com/authorizon/fastapi_websocket_pubsub) - The classic pub/sub pattern made easily accessible and scalable over the web and across your cloud in realtime.
```

2021-02-08 02:45 UTC, Kludex commented on README.md
> +- [⚡ FastAPI Websocket RPC](https://github.com/authorizon/fastapi_websocket_rpc) - RPC (bidirectional JSON RPC) over Websockets made easy, robust, and production ready.
```suggestion
- [FastAPI Websocket RPC](https://github.com/authorizon/fastapi_websocket_rpc) - RPC (bidirectional JSON RPC) over Websockets made easy, robust, and production ready.
```

2021-02-23 11:48 UTC, orweis commented
Hi @mjhea0, 
The public has called these packages awesome - "This is awesome, much gratitude for this!"
https://www.reddit.com/r/FastAPI/comments/lpriit/fastapi_websocket_rpc_and_pubsub_packages/
Any chance we can move forward with the PR ?

2021-02-23 13:47 UTC, merged